-- Generated by Mocodo 4.2.12

CREATE TABLE Animal (
  PRIMARY KEY (id_Animal),
  id_Animal      VARCHAR(42) NOT NULL,
  nom            VARCHAR(42),
  type           VARCHAR(42),
  race           VARCHAR(42),
  age            VARCHAR(42),
  poids          VARCHAR(42),
  reference      VARCHAR(42),
  id_Utilisateur VARCHAR(42) NOT NULL
);

CREATE TABLE Avis (
  PRIMARY KEY (id_Avis),
  id_Avis                    VARCHAR(42) NOT NULL,
  note_etoiles_ou_score_sur5 VARCHAR(42),
  commentaire                VARCHAR(42),
  date_avis                  VARCHAR(42),
  auteur_avis                VARCHAR(42),
  id_Utilisateur             VARCHAR(42) NOT NULL
);

CREATE TABLE Paiement (
  PRIMARY KEY (id_Paiement),
  id_Paiement          VARCHAR(42) NOT NULL,
  montant              VARCHAR(42),
  date_paiement        VARCHAR(42),
  mode_paiement_stripe VARCHAR(42)
);

CREATE TABLE Reservation (
  PRIMARY KEY (id_Reservation),
  id_Reservation VARCHAR(42) NOT NULL,
  date_debut     VARCHAR(42),
  date_fin       VARCHAR(42),
  statut         VARCHAR(42),
  id_Paiement    VARCHAR(42) NOT NULL,
  id_Service     VARCHAR(42) NOT NULL,
  id_Utilisateur VARCHAR(42) NOT NULL,
  id_Animal      VARCHAR(42) NOT NULL,
  UNIQUE (id_Paiement)
);

CREATE TABLE Service (
  PRIMARY KEY (id_Service),
  id_Service       VARCHAR(42) NOT NULL,
  type_Reservation VARCHAR(42),
  tarif            VARCHAR(42)
);

CREATE TABLE Utilisateur (
  PRIMARY KEY (id_Utilisateur),
  id_Utilisateur VARCHAR(42) NOT NULL,
  nom            VARCHAR(42),
  prenom         VARCHAR(42),
  Email          VARCHAR(42),
  Mot_de_passe   VARCHAR(42),
  telephone      VARCHAR(42),
  Adresse        VARCHAR(42)
);

ALTER TABLE Animal ADD FOREIGN KEY (id_Utilisateur) REFERENCES Utilisateur (id_Utilisateur);

ALTER TABLE Avis ADD FOREIGN KEY (id_Utilisateur) REFERENCES Utilisateur (id_Utilisateur);

ALTER TABLE Reservation ADD FOREIGN KEY (id_Animal) REFERENCES Animal (id_Animal);
ALTER TABLE Reservation ADD FOREIGN KEY (id_Utilisateur) REFERENCES Utilisateur (id_Utilisateur);
ALTER TABLE Reservation ADD FOREIGN KEY (id_Service) REFERENCES Service (id_Service);
ALTER TABLE Reservation ADD FOREIGN KEY (id_Paiement) REFERENCES Paiement (id_Paiement);
